### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by danielpacak** [open-policy-agent/golang-opa-wasm#8]
Is this project maintained and supposed to be used in production code? Or should I use wasm module from the main opa repo?

**Comment by srenatus** [comment]
Sorry for the radio silence here. We've indeed been internalizing this code into `opa` (https://github.com/open-policy-agent/opa/tree/main/internal/wasm/sdk) and should consider backporting the changes...

What's your use case? If you'd like, you can use OPA's rego package to evaluate policies via wasm, pretty transparently. You'd pass `rego.Target("wasm")` to your `rego.New(...)` call, and proceed as before. (@danielpacak you surely know this already, just stating it here for the casual reader.)

**Comment by danielpacak** [comment]
> Sorry for the radio silence here. We've indeed been internalizing this code into `opa` (https://github.com/open-policy-agent/opa/tree/main/internal/wasm/sdk) and should consider backporting the changes...
> 
> What's your use case? If you'd like, you can use OPA's rego package to evaluate policies via wasm, pretty transparently. You'd pass `rego.Target("wasm")` to your `rego.New(...)` call, and proceed as before. (@danielpacak you surely know this already, just stating it here for the casual reader.)

No worries @srenatus. My use case was just to switch from rego to wasm target and benchmark a few policies.
  
Before we discovered the `rego.Target` option we actually bumped into this repository and imported it into our project. What was maybe a bit confusing is the statement in the README **Work in Progress -- Contributions welcome!**, but thanks for clarifying it.
